# 한국환경공단 대기오염정보

## 한국환경공단_측정소정보
- [링크](https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15073877)

In [28]:
import numpy as np
import pandas as pd

In [56]:
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus

skey = 'enter sevicekey' #

url = 'http://apis.data.go.kr/B552584/MsrstnInfoInqireSvc/getNearbyMsrstnList'
params = '?' + \
urlencode({quote_plus('ServiceKey') : skey, quote_plus('serviceKey') : skey,
          quote_plus('tmX'): '244148.546388',
           quote_plus('tmY'): '412423.75772',
           quote_plus('ver'): '1.0'})
# print(url + params)

request = Request(url + params)
request.get_method = lambda: 'GET'
response_body = urlopen(request).read()
# print(response_body)

In [44]:
from xml.etree import ElementTree

root = ElementTree.fromstring(response_body)
for item in root.iter('item'):
    item_dict = {}
    item_dict['stationName'] = item.find('stationName').text
    item_dict['addr'] = item.find('addr').text
    item_dict['tm'] = item.find('tm').text
    print(item_dict)

{'stationName': '대정읍', 'addr': '제주특별자치도 서귀포시 대정읍 동일하모로149번길 21-8대정청소년수련관', 'tm': '1236.7'}
{'stationName': '고산리', 'addr': '제주 제주시 한경면 고산리3762', 'tm': '1238.7'}
{'stationName': '동홍동', 'addr': '제주 서귀포시 동홍동 453-1(서귀포소방서)서귀포소방서', 'tm': '1253.9'}

In [46]:
df = pd.DataFrame()
for item in root.iter('item'):
    item_dict = {}
    item_dict['stationName'] = item.find('stationName').text
    item_dict['addr'] = item.find('addr').text
    item_dict['tm'] = item.find('tm').text
    df = df.append(item_dict, ignore_index=True)

df

                                       addr stationName      tm
0  제주특별자치도 서귀포시 대정읍 동일하모로149번길 21-8대정청소년수련관         대정읍  1236.7
1                        제주 제주시 한경면 고산리3762         고산리  1238.7
2           제주 서귀포시 동홍동 453-1(서귀포소방서)서귀포소방서         동홍동  1253.9

## 한국환경공단_대기오염 정보

### 측정소별 실시간 측정정보 조회

In [57]:
skey2= 'enter serviekey' #

url = 'http://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getMsrstnAcctoRltmMesureDnsty'
params = '?' + \
urlencode({quote_plus('ServiceKey') : skey2, 
           quote_plus('serviceKey') : skey2, 
           quote_plus('returnType') : 'xml', 
           quote_plus('numOfRows') : '100', 
           quote_plus('pageNo') : '1', 
           quote_plus('stationName') : '종로구', 
           quote_plus('dataTerm') : 'DAILY', 
           quote_plus('ver') : '1.0' })

# print(url + params)
request = Request(url + params)
request.get_method = lambda: 'GET'
response_body = urlopen(request).read()

In [51]:
root = ElementTree.fromstring(response_body)
for item in root.iter('item'):
    item_dict = {}
    item_dict['so2Grade'] = item.find('so2Grade').text
    item_dict['khaiValue'] = item.find('khaiValue').text
    item_dict['so2Value'] = item.find('so2Value').text
    item_dict['coValue'] = item.find('coValue').text
    item_dict['pm10Value'] = item.find('pm10Value').text
    item_dict['o3Grade'] = item.find('o3Grade').text
    item_dict['khaiGrade'] = item.find('khaiGrade').text
    item_dict['pm25Value'] = item.find('pm25Value').text
    item_dict['no2Grade'] = item.find('no2Grade').text
    item_dict['pm25Grade'] = item.find('pm25Grade').text
    item_dict['dataTime'] = item.find('dataTime').text
    item_dict['coGrade'] = item.find('coGrade').text
    item_dict['no2Value'] = item.find('no2Value').text
    item_dict['pm10Grade'] = item.find('pm10Grade').text
    item_dict['o3Value'] = item.find('o3Value').text
    print(item_dict)

{'so2Grade': '1', 'khaiValue': '76', 'so2Value': '0.003', 'coValue': '0.8', 'pm10Value': '40', 'o3Grade': '1', 'khaiGrade': '2', 'pm25Value': '26', 'no2Grade': '2', 'pm25Grade': '2', 'dataTime': '2021-10-02 24:00', 'coGrade': '1', 'no2Value': '0.046', 'pm10Grade': '2', 'o3Value': '0.005'}
{'so2Grade': '1', 'khaiValue': '69', 'so2Value': '0.003', 'coValue': '0.7', 'pm10Value': '41', 'o3Grade': '1', 'khaiGrade': '2', 'pm25Value': '25', 'no2Grade': '2', 'pm25Grade': '2', 'dataTime': '2021-10-02 23:00', 'coGrade': '1', 'no2Value': '0.037', 'pm10Grade': '2', 'o3Value': '0.019'}
{'so2Grade': '1', 'khaiValue': '66', 'so2Value': '0.004', 'coValue': '0.7', 'pm10Value': '43', 'o3Grade': '1', 'khaiGrade': '2', 'pm25Value': '27', 'no2Grade': '2', 'pm25Grade': '2', 'dataTime': '2021-10-02 22:00', 'coGrade': '1', 'no2Value': '0.038', 'pm10Grade': '2', 'o3Value': '0.022'}
{'so2Grade': '1', 'khaiValue': '64', 'so2Value': '0.003', 'coValue': '0.7', 'pm10Value': '46', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '30', 'no2Grade': '2', 'pm25Grade': '2', 'dataTime': '2021-10-02 21:00', 'coGrade': '1', 'no2Value': '0.033', 'pm10Grade': '2', 'o3Value': '0.036'}
{'so2Grade': '1', 'khaiValue': '63', 'so2Value': '0.004', 'coValue': '0.6', 'pm10Value': '40', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '25', 'no2Grade': '1', 'pm25Grade': '2', 'dataTime': '2021-10-02 20:00', 'coGrade': '1', 'no2Value': '0.030', 'pm10Grade': '2', 'o3Value': '0.046'}
{'so2Grade': '1', 'khaiValue': '73', 'so2Value': '0.004', 'coValue': '0.5', 'pm10Value': '38', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '25', 'no2Grade': '1', 'pm25Grade': '2', 'dataTime': '2021-10-02 19:00', 'coGrade': '1', 'no2Value': '0.027', 'pm10Grade': '1', 'o3Value': '0.057'}
{'so2Grade': '1', 'khaiValue': '76', 'so2Value': '0.003', 'coValue': '0.5', 'pm10Value': '32', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '19', 'no2Grade': '1', 'pm25Grade': '2', 'dataTime': '2021-10-02 18:00', 'coGrade': '1', 'no2Value': '0.020', 'pm10Grade': '1', 'o3Value': '0.061'}
{'so2Grade': '1', 'khaiValue': '84', 'so2Value': '0.004', 'coValue': '0.4', 'pm10Value': '31', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '19', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 17:00', 'coGrade': '1', 'no2Value': '0.015', 'pm10Grade': '1', 'o3Value': '0.071'}
{'so2Grade': '1', 'khaiValue': '83', 'so2Value': '0.003', 'coValue': '0.4', 'pm10Value': '28', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '14', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 16:00', 'coGrade': '1', 'no2Value': '0.014', 'pm10Grade': '1', 'o3Value': '0.070'}
{'so2Grade': '1', 'khaiValue': '83', 'so2Value': '0.003', 'coValue': '0.4', 'pm10Value': '31', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '21', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 15:00', 'coGrade': '1', 'no2Value': '0.016', 'pm10Grade': '1', 'o3Value': '0.069'}
{'so2Grade': '1', 'khaiValue': '74', 'so2Value': '0.003', 'coValue': '0.4', 'pm10Value': '34', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '20', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 14:00', 'coGrade': '1', 'no2Value': '0.019', 'pm10Grade': '1', 'o3Value': '0.059'}
{'so2Grade': '1', 'khaiValue': '68', 'so2Value': '0.003', 'coValue': '0.4', 'pm10Value': '30', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '16', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 13:00', 'coGrade': '1', 'no2Value': '0.019', 'pm10Grade': '1', 'o3Value': '0.051'}
{'so2Grade': '1', 'khaiValue': '60', 'so2Value': '0.003', 'coValue': '0.4', 'pm10Value': '26', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '13', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 12:00', 'coGrade': '1', 'no2Value': '0.022', 'pm10Grade': '1', 'o3Value': '0.042'}
{'so2Grade': '1', 'khaiValue': '53', 'so2Value': '0.003', 'coValue': '0.4', 'pm10Value': '24', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '11', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 11:00', 'coGrade': '1', 'no2Value': '0.025', 'pm10Grade': '1', 'o3Value': '0.033'}
{'so2Grade': '1', 'khaiValue': '47', 'so2Value': '0.003', 'coValue': '0.5', 'pm10Value': '18', 'o3Grade': '1', 'khaiGrade': '1', 'pm25Value': '7', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 10:00', 'coGrade': '1', 'no2Value': '0.028', 'pm10Grade': '1', 'o3Value': '0.020'}
{'so2Grade': '1', 'khaiValue': '47', 'so2Value': '0.003', 'coValue': '0.4', 'pm10Value': '15', 'o3Grade': '1', 'khaiGrade': '1', 'pm25Value': '7', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 09:00', 'coGrade': '1', 'no2Value': '0.028', 'pm10Grade': '1', 'o3Value': '0.015'}
{'so2Grade': '1', 'khaiValue': '50', 'so2Value': '0.003', 'coValue': '0.4', 'pm10Value': '14', 'o3Grade': '1', 'khaiGrade': '1', 'pm25Value': '7', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 08:00', 'coGrade': '1', 'no2Value': '0.030', 'pm10Grade': '1', 'o3Value': '0.012'}
{'so2Grade': '1', 'khaiValue': '38', 'so2Value': '0.003', 'coValue': '0.4', 'pm10Value': '13', 'o3Grade': '1', 'khaiGrade': '1', 'pm25Value': '7', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 07:00', 'coGrade': '1', 'no2Value': '0.022', 'pm10Grade': '1', 'o3Value': '0.023'}
{'so2Grade': '1', 'khaiValue': '42', 'so2Value': '0.003', 'coValue': '0.4', 'pm10Value': '11', 'o3Grade': '1', 'khaiGrade': '1', 'pm25Value': '7', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 06:00', 'coGrade': '1', 'no2Value': '0.019', 'pm10Grade': '1', 'o3Value': '0.025'}
{'so2Grade': '1', 'khaiValue': '48', 'so2Value': '0.002', 'coValue': '0.4', 'pm10Value': '11', 'o3Grade': '1', 'khaiGrade': '1', 'pm25Value': '9', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 05:00', 'coGrade': '1', 'no2Value': '0.016', 'pm10Grade': '1', 'o3Value': '0.029'}
{'so2Grade': '1', 'khaiValue': '48', 'so2Value': '0.003', 'coValue': '0.4', 'pm10Value': '10', 'o3Grade': '1', 'khaiGrade': '1', 'pm25Value': '7', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 04:00', 'coGrade': '1', 'no2Value': '0.016', 'pm10Grade': '1', 'o3Value': '0.029'}
{'so2Grade': '1', 'khaiValue': '58', 'so2Value': '0.003', 'coValue': '0.3', 'pm10Value': '9', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '8', 'no2Grade': '1', 'pm25Grade': '1', 'dataTime': '2021-10-02 03:00', 'coGrade': '1', 'no2Value': '0.015', 'pm10Grade': '1', 'o3Value': '0.039'}
{'so2Grade': '1', 'khaiValue': '59', 'so2Value': '0.003', 'coValue': '0.3', 'pm10Value': '9', 'o3Grade': '2', 'khaiGrade': '2', 'pm25Value': '6', 'no2Grade': '1', 'pm25Grade': '2', 'dataTime': '2021-10-02 02:00', 'coGrade': '1', 'no2Value': '0.014', 'pm10Grade': '1', 'o3Value': '0.041'}

In [52]:
df = pd.DataFrame()
for item in root.iter('item'):
    item_dict = {}
    item_dict['so2Grade'] = item.find('so2Grade').text
    item_dict['khaiValue'] = item.find('khaiValue').text
    item_dict['so2Value'] = item.find('so2Value').text
    item_dict['coValue'] = item.find('coValue').text
    item_dict['pm10Value'] = item.find('pm10Value').text
    item_dict['o3Grade'] = item.find('o3Grade').text
    item_dict['khaiGrade'] = item.find('khaiGrade').text
    item_dict['pm25Value'] = item.find('pm25Value').text
    item_dict['no2Grade'] = item.find('no2Grade').text
    item_dict['pm25Grade'] = item.find('pm25Grade').text
    item_dict['dataTime'] = item.find('dataTime').text
    item_dict['coGrade'] = item.find('coGrade').text
    item_dict['no2Value'] = item.find('no2Value').text
    item_dict['pm10Grade'] = item.find('pm10Grade').text
    item_dict['o3Value'] = item.find('o3Value').text
    df = df.append(item_dict, ignore_index=True)

df

   coGrade coValue          dataTime  ... pm25Value so2Grade so2Value
0        1     0.8  2021-10-02 24:00  ...        26        1    0.003
1        1     0.7  2021-10-02 23:00  ...        25        1    0.003
2        1     0.7  2021-10-02 22:00  ...        27        1    0.004
3        1     0.7  2021-10-02 21:00  ...        30        1    0.003
4        1     0.6  2021-10-02 20:00  ...        25        1    0.004
5        1     0.5  2021-10-02 19:00  ...        25        1    0.004
6        1     0.5  2021-10-02 18:00  ...        19        1    0.003
7        1     0.4  2021-10-02 17:00  ...        19        1    0.004
8        1     0.4  2021-10-02 16:00  ...        14        1    0.003
9        1     0.4  2021-10-02 15:00  ...        21        1    0.003
10       1     0.4  2021-10-02 14:00  ...        20        1    0.003
11       1     0.4  2021-10-02 13:00  ...        16        1    0.003
12       1     0.4  2021-10-02 12:00  ...        13        1    0.003
13       1     0.4  2021-10-02 11:00  ...        11        1    0.003
14       1     0.5  2021-10-02 10:00  ...         7        1    0.003
15       1     0.4  2021-10-02 09:00  ...         7        1    0.003
16       1     0.4  2021-10-02 08:00  ...         7        1    0.003
17       1     0.4  2021-10-02 07:00  ...         7        1    0.003
18       1     0.4  2021-10-02 06:00  ...         7        1    0.003
19       1     0.4  2021-10-02 05:00  ...         9        1    0.002
20       1     0.4  2021-10-02 04:00  ...         7        1    0.003
21       1     0.3  2021-10-02 03:00  ...         8        1    0.003
22       1     0.3  2021-10-02 02:00  ...         6        1    0.003

[23 rows x 15 columns]

### 시도별 실시간 측정정보 조회

In [58]:
url = 'http://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty'
params = '?' + \
urlencode({quote_plus('serviceKey') : skey2, 
           quote_plus('returnType') : 'xml', 
           quote_plus('numOfRows') : '100', 
           quote_plus('pageNo') : '1', 
           quote_plus('sidoName') : '서울', 
           quote_plus('ver') : '1.0' })

# print(url + params)
request = Request(url + params)
request.get_method = lambda: 'GET'
response_body = urlopen(request).read()

In [55]:
root = ElementTree.fromstring(response_body)

df = pd.DataFrame()
for item in root.iter('item'):
    item_dict = {}
    item_dict['so2Grade'] = item.find('so2Grade').text
    item_dict['khaiValue'] = item.find('khaiValue').text
    item_dict['so2Value'] = item.find('so2Value').text
    item_dict['coValue'] = item.find('coValue').text
    item_dict['pm10Value'] = item.find('pm10Value').text
    item_dict['o3Grade'] = item.find('o3Grade').text
    item_dict['khaiGrade'] = item.find('khaiGrade').text
    item_dict['pm25Value'] = item.find('pm25Value').text
    item_dict['no2Grade'] = item.find('no2Grade').text
    item_dict['pm25Grade'] = item.find('pm25Grade').text
    item_dict['dataTime'] = item.find('dataTime').text
    item_dict['coGrade'] = item.find('coGrade').text
    item_dict['no2Value'] = item.find('no2Value').text
    item_dict['pm10Grade'] = item.find('pm10Grade').text
    item_dict['o3Value'] = item.find('o3Value').text
    item_dict['stationName'] = item.find('stationName').text
    item_dict['sidoName'] = item.find('sidoName').text
    df = df.append(item_dict, ignore_index=True)

df

   coGrade coValue          dataTime  ... so2Grade so2Value stationName
0        1     0.6  2021-10-03 01:00  ...        1    0.003          중구
1        1     0.8  2021-10-03 01:00  ...        1    0.004        한강대로
2        1     0.7  2021-10-03 01:00  ...        1    0.003         종로구
3        1     0.7  2021-10-03 01:00  ...        1    0.004        청계천로
4        1     0.7  2021-10-03 01:00  ...        1    0.003          종로
5        1     0.5  2021-10-03 01:00  ...        1    0.003         용산구
6        1     0.7  2021-10-03 01:00  ...        1    0.002         광진구
7        1     0.5  2021-10-03 01:00  ...        1    0.003         성동구
8        1     0.6  2021-10-03 01:00  ...        1    0.003        강변북로
9        1     0.5  2021-10-03 01:00  ...        1    0.003         중랑구
10       1     0.7  2021-10-03 01:00  ...        1    0.003        동대문구
11       1     0.8  2021-10-03 01:00  ...        1    0.003         홍릉로
12       1     0.9  2021-10-03 01:00  ...        1    0.003         성북구
13       1     0.8  2021-10-03 01:00  ...        1    0.002         정릉로
14       1     0.7  2021-10-03 01:00  ...     None        -         도봉구
15       1     0.6  2021-10-03 01:00  ...        1    0.003         은평구
16       1     0.6  2021-10-03 01:00  ...        1    0.003        서대문구
17       1     0.5  2021-10-03 01:00  ...        1    0.004         마포구
18       1     1.0  2021-10-03 01:00  ...        1    0.003         신촌로
19       1     0.5  2021-10-03 01:00  ...        1    0.003         강서구
20       1     0.4  2021-10-03 01:00  ...        1    0.003        공항대로
21       1     0.5  2021-10-03 01:00  ...        1    0.003         구로구
22       1     0.4  2021-10-03 01:00  ...        1    0.003        영등포구
23       1     0.5  2021-10-03 01:00  ...        1    0.003        영등포로
24       1     0.5  2021-10-03 01:00  ...        1    0.002         동작구
25       1     0.8  2021-10-03 01:00  ...        1    0.003   동작대로 중앙차로
26       1     0.7  2021-10-03 01:00  ...        1    0.003         관악구
27       1     0.6  2021-10-03 01:00  ...        1    0.003         강남구
28       1     0.5  2021-10-03 01:00  ...        1    0.003         서초구
29       1     0.8  2021-10-03 01:00  ...        1    0.003        도산대로
30       1     0.8  2021-10-03 01:00  ...        1    0.002        강남대로
31       1     0.6  2021-10-03 01:00  ...        1    0.003         송파구
32       1     0.6  2021-10-03 01:00  ...        1    0.002         강동구
33       1     0.6  2021-10-03 01:00  ...        1    0.002        천호대로
34       1     0.4  2021-10-03 01:00  ...        1    0.003         금천구
35       1     0.5  2021-10-03 01:00  ...        1    0.004        시흥대로
36       1     0.5  2021-10-03 01:00  ...        1    0.003         강북구
37       1     0.4  2021-10-03 01:00  ...        1    0.003         양천구
38       1     0.6  2021-10-03 01:00  ...        1    0.002         노원구
39       1     0.6  2021-10-03 01:00  ...        1    0.003         화랑로

[40 rows x 17 columns]